<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="css/reset.css">
    <link rel="stylesheet" href="css/datatables.min.css">
    <link rel="stylesheet" href="css/simple-grid.css">
    <link rel="stylesheet" href="css/estils.css">
    <link rel="stylesheet" href="css/navbarmenu.css">
    <title>Pilones</title>
</head>
<body>
    <div class="container">
        <div id="divtaula" class="row">
            <div class="col-12">
                <div class="titolknob">Llistat d'usuaris'</div>
                <div id="lataula" class="taules">
                    <table class="datatable" id="taula">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Nom</th>
                                <th>Cognoms</th>
                                <th>DNI</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</body>
<script type="text/javascript" src="js/jquery.js"></script>
<script type="text/javascript" src="js/jquery.knob.min.js"></script>
<script type="text/javascript" src="js/datatables.min.js"></script>
<script type="text/javascript" src="xjs/chart.min.js"></script>
<script type="text/javascript" src="js/Chart.bundle.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        console.log("http://pilones/usuari/llista");
        // ****************
        // Llistat Usuaris
        $('#taula').DataTable({
            responsive: true,
            autoWidth: false,
            ajax: "http://pilones/usuari/llista",
            columns: [
                { "data": "idusuari", "width": "5%" },
                { "data": "nom", "width": "25%" },
                { "data": "cognoms", "width": "15%" },
                { "data": "dni", "width": "5%" },
            ],
            columnDefs: [
                { responsivePriority: 1, targets: 1 },
                { responsivePriority: 2, targets: 0 },
                { responsivePriority: 3, targets: 2 },
                { responsivePriority: 4, targets: 3 }
            ],
        });
    });
</script>
</html>
