<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="css/reset.css">
    <link rel="stylesheet" href="css/datatables.min.css">
    <link rel="stylesheet" href="css/simple-grid.css">
    <link rel="stylesheet" href="css/navbarmenu.css">
    <link rel="stylesheet" href="css/estils.css">
    <link rel="stylesheet" href="css/taules.css">
    <link rel="stylesheet" type="text/css" href="mapplic/mapplic/mapplic.css">
    <link rel="stylesheet" type="text/css" href="css/font-awesome/css/font-awesome.min.css">
    <title>Pilones</title>
</head>
<body>
    <div class="container">
        <div id="knobs" class="row">
            <div class="col-2 col-4-sm">
                <div class="titolknob">Ocupació H<sub>2</sub>O</div>
                <input type="text" value="0" class="knh2o">
            </div>
            <div class="col-2 col-4-sm">
                <div class="titolknob">Ocupació Elec</div>
                <input type="text" value="0" class="knelec">
            </div>
            <div class="col-2 col-4-sm">
                <div class="titolknob">Anomalies total</div>
                <input type="text" value="0" class="knanomalia">
            </div>
        </div>
        <div id="divtaula" class="row">
            <div class="col-12">
                <div class="titolknob">Últims moviments</div>
                <div id="lataula" class="taules">
                    <table class="datatable stripe" id="taula">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Data/hora</th>
                                <th>Valor</th>
                                <th>Sensor</th>
                                <th>Missatge</th>
                                <th>Tipus</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="titolknob">Consum última setmana</div>
                <canvas id="grafconsums" height="350" width="900"></canvas>
            </div>
        </div>
        <div id="mapa" class="row">
            <div class="col-12">
                <div class="titolknob">Mapa de pilones</div>
                <br />
                <div id="mapplic"></div>
            </div>
        </div>
        <div id="taules" class="row">
            <div class="col-12">
                <p>Una taula 5</p>
            </div>
        </div>
    </div>

</body>
<script type="text/javascript" src="js/jquery.js"></script>
<script type="text/javascript" src="js/jquery.knob.min.js"></script>
<script type="text/javascript" src="js/datatables.min.js"></script>
<script type="text/javascript" src="xjs/chart.min.js"></script>
<script type="text/javascript" src="js/Chart.bundle.min.js"></script>
<script type="text/javascript" src="js/waindex.js"></script>
<script type="text/javascript" src="mapplic/js/hammer.min.js"></script>
<script type="text/javascript" src="mapplic/js/jquery.mousewheel.js"></script>
<script type="text/javascript" src="mapplic/mapplic/mapplic.js"></script>
<script type="text/javascript">

</script>
</html>
