<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="css/reset.css">
    <link rel="stylesheet" href="css/datatables.min.css">
    <link rel="stylesheet" href="css/simple-grid.css">
    <link rel="stylesheet" href="css/estils.css">
    <link rel="stylesheet" href="css/navbarmenu.css">
    <title>Pilones</title>
</head>
<body>
    <header>
            <div class="elmenu">
                <a href="/" class="linkmenu">
                    <div class="dinsmenu descripcio">home</div>
                    <div class="dinsmenu imatge"><img src="images/home-gris.svg" /></div>
                </a>
            </div>
            <div class="elmenu">
                <a href="usuaris" class="linkmenu">
                    <div class="dinsmenu descripcio">usuaris</div>
                    <div class="dinsmenu imatge"><img src="images/avatar-gris.svg" /></div>
                </a>
            </div>
            <div class="elmenu">
                <a href="" class="linkmenu">
                    <div class="dinsmenu descripcio">h2o</div>
                    <div class="dinsmenu imatge"><img src="images/tap-gris.svg" /></div>
                </a>
            </div>
            <div class="elmenu">
                <a href="" class="linkmenu">
                    <div class="dinsmenu descripcio">elec</div>
                    <div class="dinsmenu imatge"><img src="images/light-bulb-gris.svg" /></div>
                </a>
            </div>
            <div class="elmenu">
                <a href="" class="linkmenu">
                    <div class="dinsmenu descripcio">gràfs</div>
                    <div class="dinsmenu imatge"><img src="images/chart-gris.svg" /></div>
                </a>
            </div>
            <div class="elmenu">
                <a href="" class="linkmenu">
                    <div class="dinsmenu descripcio">fact</div>
                    <div class="dinsmenu imatge"><img src="images/euro-gris.svg" /></div>
                </a>
            </div>
            <div class="elmenu">
                <a href="" class="linkmenu">
                    <div class="dinsmenu descripcio">logout</div>
                    <div class="dinsmenu imatge"><img src="images/power-button-sign-gris.svg" /></div>
                </a>
            </div>
    </header>
    <div class="container">
        <div id="knobs" class="row">
            <div class="col-2 col-4-sm">
                <div class="titolknob">Ocupació H<sub>2</sub>O</div>
                <input type="text" value="0" class="knh2o">
            </div>
            <div class="col-2 col-4-sm">
                <div class="titolknob">Ocupació Elec</div>
                <input type="text" value="0" class="knelec">
            </div>
            <div class="col-2 col-4-sm">
                <div class="titolknob">Anomalies total</div>
                <input type="text" value="0" class="knanomalia">
            </div>
        </div>
        <div id="divtaula" class="row">
            <div class="col-12">
                <div class="titolknob">Últims moviments</div>
                <div id="lataula" class="taules">
                    <table class="datatable" id="taula">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Data/hora</th>
                                <th>Valor</th>
                                <th># sensor</th>
                                <th>Missatge</th>
                                <th>Tipus</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div id="divgrafica" class="row">
            <div id="graficrow" class="col-12">
                <div class="titolknob">Consums</div>
                <canvas id="myChart" height="350" width="900"></canvas>
            </div>
        </div>
        <div id="taula" class="row">
            <div class="col-12">
                Últims moviments: <span id="ultims"></span>
            </div>
        </div>
        <div id="taules" class="row">
            <div class="col-12">
                <p>Una taula 4</p>
            </div>
        </div>
        <div id="taules" class="row">
            <div class="col-12">
                <p>Una taula 5</p>
            </div>
        </div>
        <div id="taules" class="row">
            <div class="col-12">
                <p>Una taula 6</p>
            </div>
        </div>
        <div id="taules" class="row">
            <div class="col-12">
                <p>Una taula 7</p>
            </div>
        </div>
        <div id="taules" class="row">
            <div class="col-12">
                <p>Una taula 8</p>
            </div>
        </div>
        <div id="taules" class="row">
            <div class="col-12">
                <p>Una taula 9</p>
            </div>
        </div>
        <div id="taules" class="row">
            <div class="col-12">
                <p>Una taula 10</p>
            </div>
        </div>
        <div id="taules" class="row">
            <div class="col-12">
                <p>Una taula 11</p>
            </div>
        </div>
        <div id="taules" class="row">
            <div class="col-12">
                <p>Una taula 12</p>
            </div>
        </div>
        <div id="taules" class="row">
            <div class="col-12">
                <p>Una taula 13</p>
            </div>
        </div>
        <div id="taules" class="row">
            <div class="col-12">
                <p>Una taula 14</p>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <p>Una taula 14</p>
            </div>
        </div>
    </div>
</body>
<script type="text/javascript" src="js/jquery.js"></script>
<script type="text/javascript" src="js/jquery.knob.min.js"></script>
<script type="text/javascript" src="js/datatables.min.js"></script>
<script type="text/javascript" src="xjs/chart.min.js"></script>
<script type="text/javascript" src="js/Chart.bundle.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        // ****************
        // knobs
        var estat = "lliure";
        var tph2o = 0;
        var tpelec = 0;
        var tpanomalia = 0;
        var nanomalia =0;
        var nsensors = 0;

        // knob H2O
        $.ajax({
            url: window.location.href + "h2o/total/status",
            async: false,
            success: function(result) {
                var total = 0;
                var nestat = 0;
                $.map(result, function(elm) {
                    total += +elm.total;
                    nestat = (elm.estat === estat) ? elm.total : nestat;
                    nanomalia = (elm.estat === "anomalia") ? (nanomalia + elm.total) : nanomalia;
                    return elm;
                });
                tph2o = +(100 * +nestat / total);
                nsensors += total;
            }
        });
        var colorestat = (estat == "lliure") ? "#aadeff" : ((estat == "ocupat") ? "#3333ff" : "#ff0000");
        $(".knh2o").knob({
            width: '100%',
            height: '100%',
            fgColor: colorestat,
            readOnly: true,
        });
        $(".knh2o").val(tph2o).trigger('change');

        // knob Elec
        $.ajax({
            url: window.location.href + "elec/total/status",
            async: false,
            success: function(result) {
                var total = 0;
                var nestat = 0;
                $.map(result, function(elm) {
                    total += +elm.total;
                    nestat = (elm.estat === estat) ? elm.total : nestat;
                    nanomalia = (elm.estat === "anomalia") ? (nanomalia + elm.total) : nanomalia;
                    return elm;
                });
                tpelec = +(100 * +nestat / total);
                nsensors += total;
            }
        });
        var colorestat = (estat == "lliure") ? "#FFC200" : ((estat == "ocupat") ? "#FF8500" : "#FF0000");
        $(".knelec").knob({
            width: '100%',
            height: '100%',
            fgColor: colorestat,
            readOnly: true,
        });
        $(".knelec").val(tpelec).trigger('change');

        // knob Anomalia
        tpanomalia = +(100 * +nanomalia / nsensors);
        var colorestat = (estat == "anomalia") ? "#FFC200" : ((estat == "ocupat") ? "#FF8500" : "#FF0000");
        $(".knanomalia").knob({
            width: '100%',
            height: '100%',
            fgColor: colorestat,
            readOnly: true,
        });
        $(".knanomalia").val(tpanomalia).trigger('change');

        // ****************
        // Taula 1
        $('#taula').DataTable({
            responsive: true,
            autoWidth: false,
            ajax: window.location.href + "sensors/regs",
            columns: [
                { "data": "idregh2o", "width": "5%" },
                { "data": "datareg", "width": "25%" },
                { "data": "valor", "width": "15%" },
                { "data": "idsensorh2o", "width": "5%" },
                { "data": "missatge", "width": "20%" },
                { "data": "tipus", "width": "15%" }
            ],
            columnDefs: [
                { responsivePriority: 1, targets: 0 },
                { responsivePriority: 2, targets: -1 },
                { responsivePriority: 3, targets: 1 },
                { responsivePriority: 4, targets: 2 },
                { responsivePriority: 5, targets: 3 },
                { responsivePriority: 6, targets: 4 },
                { responsivePriority: 7, targets: 5 }
            ],
        });

        // ****************
        // Chart
        var ctx = $("#myChart");
        var myChart = new Chart(ctx, {
            type: 'bar',
            responsive: true,
            data: {
                labels: ["dilluns", "dimarts", "dimecres", "dijous", "divendres", "dissabte","diumenge"],
                datasets: [
                    {
                        label: 'H2O',
                        data: [1200, 1900, 300, 500, 200, 300, 700],
                        backgroundColor: '#aadeff',
                        borderColor: '#aadeff',
                        borderWidth: 1
                    },
                    {
                        label: 'Elec',
                        data: [15, 21, 7, 3, 6, 9, 7],
                        backgroundColor: '#FFC200',
                        borderColor: '#FFC200',
                        borderWidth: 1
                    },
                ]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: false,
                        }
                    }]
                }
            }
        });
        $('#ultims').html('hola');
    });

    /* menu */
    $(window).scroll(function() {
        if ($(this).scrollTop() > 25){  
            $('header').addClass("sticky");
            $('.descripcio').hide();
        }
        else{
            if ($(window).width() >= 720 ){
                $('header').removeClass("sticky");
                $('.descripcio').show();
            }
            else {
                $('header').removeClass("sticky");
            }
        }
    });
    /* end menu */
</script>
</html>
