<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="css/reset.css">
    <link rel="stylesheet" href="css/datatables.min.css">
    <link rel="stylesheet" href="css/simple-grid.css">
    <link rel="stylesheet" href="css/navbarmenu.css">
    <link rel="stylesheet" href="css/estils.css">
    <link rel="stylesheet" href="css/taules.css">
    <title>Pilones</title>
</head>
<body>
    <header>
            <div class="elmenu">
                <a href="/" class="linkmenu">
                    <div class="dinsmenu descripcio">home</div>
                    <div class="dinsmenu imatge"><img src="images/home-gris.svg" /></div>
                </a>
            </div>
            <div class="elmenu">
                <a href="usuaris" class="linkmenu">
                    <div class="dinsmenu descripcio">usuaris</div>
                    <div class="dinsmenu imatge"><img src="images/avatar-gris.svg" /></div>
                </a>
            </div>
            <div class="elmenu">
                <a href="" class="linkmenu">
                    <div class="dinsmenu descripcio">h2o</div>
                    <div class="dinsmenu imatge"><img src="images/tap-gris.svg" /></div>
                </a>
            </div>
            <div class="elmenu">
                <a href="" class="linkmenu">
                    <div class="dinsmenu descripcio">elec</div>
                    <div class="dinsmenu imatge"><img src="images/light-bulb-gris.svg" /></div>
                </a>
            </div>
            <div class="elmenu">
                <a href="" class="linkmenu">
                    <div class="dinsmenu descripcio">gràfs</div>
                    <div class="dinsmenu imatge"><img src="images/chart-gris.svg" /></div>
                </a>
            </div>
            <div class="elmenu">
                <a href="" class="linkmenu">
                    <div class="dinsmenu descripcio">fact</div>
                    <div class="dinsmenu imatge"><img src="images/euro-gris.svg" /></div>
                </a>
            </div>
            <div class="elmenu">
                <a href="" class="linkmenu">
                    <div class="dinsmenu descripcio">logout</div>
                    <div class="dinsmenu imatge"><img src="images/power-button-sign-gris.svg" /></div>
                </a>
            </div>
    </header>
    <div class="container">
        <div id="knobs" class="row">
            <div class="col-2 col-4-sm">
                <div class="titolknob">Ocupació H<sub>2</sub>O</div>
                <input type="text" value="0" class="knh2o">
            </div>
            <div class="col-2 col-4-sm">
                <div class="titolknob">Ocupació Elec</div>
                <input type="text" value="0" class="knelec">
            </div>
            <div class="col-2 col-4-sm">
                <div class="titolknob">Anomalies total</div>
                <input type="text" value="0" class="knanomalia">
            </div>
        </div>
        <div id="divtaula" class="row">
            <div class="col-12">
                <div class="titolknob">Últims moviments</div>
                <div id="lataula" class="taules">
                    <table class="datatable stripe" id="taula">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Data/hora</th>
                                <th>Valor</th>
                                <th>Sensor</th>
                                <th>Missatge</th>
                                <th>Tipus</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="titolknob">Consum última setmana</div>
                <canvas id="grafconsums" height="350" width="900"></canvas>
            </div>
        </div>
        <div id="taules" class="row">
            <div class="col-12">
                <p>Una taula 4</p>
            </div>
        </div>
        <div id="taules" class="row">
            <div class="col-12">
                <p>Una taula 5</p>
            </div>
        </div>
        <div id="taules" class="row">
            <div class="col-12">
                <p>Una taula 6</p>
            </div>
        </div>
        <div id="taules" class="row">
            <div class="col-12">
                <p>Una taula 7</p>
            </div>
        </div>
        <div id="taules" class="row">
            <div class="col-12">
                <p>Una taula 8</p>
            </div>
        </div>
        <div id="taules" class="row">
            <div class="col-12">
                <p>Una taula 9</p>
            </div>
        </div>
        <div id="taules" class="row">
            <div class="col-12">
                <p>Una taula 10</p>
            </div>
        </div>
        <div id="taules" class="row">
            <div class="col-12">
                <p>Una taula 11</p>
            </div>
        </div>
        <div id="taules" class="row">
            <div class="col-12">
                <p>Una taula 12</p>
            </div>
        </div>
        <div id="taules" class="row">
            <div class="col-12">
                <p>Una taula 13</p>
            </div>
        </div>
        <div id="taules" class="row">
            <div class="col-12">
                <p>Una taula 14</p>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <p>Una taula 14</p>
            </div>
        </div>
    </div>
</body>
<script type="text/javascript" src="js/jquery.js"></script>
<script type="text/javascript" src="js/jquery.knob.min.js"></script>
<script type="text/javascript" src="js/datatables.min.js"></script>
<script type="text/javascript" src="xjs/chart.min.js"></script>
<script type="text/javascript" src="js/Chart.bundle.min.js"></script>
<script type="text/javascript" src="js/waindex.js"></script>
<script type="text/javascript">

</script>
</html>
