<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <link rel="stylesheet" type="text/css" href="/css/estils.css" />
</head>

<body>
    <div id="graficestat">
        <input type="text" value="0" class="kndial">
    </div>
</body>

<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/jquery.knob.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        var estat = "<?php echo (isset($estat)) ? $estat : ''; ?>";
        var tplliures = 0;
        $.ajax({
            url: "http://pilones/h2o/total/status",
            async: false,
            success: function(result) {
                var total = 0;
                var nestat = 0;
                $.map(result, function(elm) {
                    total += +elm.total;
                    nestat = (elm.estat === estat) ? elm.total : nestat;
                    return elm;
                });
                tplliures = +(100 * +nestat / total);
            }
        });
        var colorestat = (estat == "lliure") ? "#aadeff" : ((estat == "ocupat") ? "#3333ff" : "#ee44ff");
        $(".kndial").knob({
            width: '100%',
            height: '100%',
            fgColor: colorestat,
            readOnly: true,
        });
        $(".kndial").val(tplliures).trigger('change');
    });
</script>
</html>
