<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" type="text/css" href="css/reset.css">
    <link rel="stylesheet" type="text/css" href="css/datatables.min.css">
    <link rel="stylesheet" type="text/css" href="xxxcss/buttons.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="css/simple-grid.css">
    <link rel="stylesheet" type="text/css" href="css/navbarmenu.css">
    <link rel="stylesheet" type="text/css" href="css/estils.css">
    <link rel="stylesheet" type="text/css" href="css/taules.css">
    <link rel="stylesheet" type="text/css" href="css/modal.css">
    <link rel="stylesheet" type="text/css" href="css/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="css/daterangepicker.min.css">
    <title>Pilones</title>
</head>
<body>
    <div id="container" class="container">
        <div id="divtaula" class="row">
            <div class="col-12">
                <div class="titolknob">Llistat d'usuaris</div>
                <div id="lataula" class="taules">
                    <table class="datatable stripe" id="taula">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Nom</th>
                                <th>Cognoms</th>
                                <th>DNI</th>
                                <th>Entrada</th>
                                <th>Sortida</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Modal -->
    <div id="myModal" class="modal">
        <!-- Modal content -->
        <div class="modal-content">
            <div id="titolmodalafegir" class="modal-header nou">Nou Usuari<span class="close">×</span></div>
            <hr /><br />
            <div class="modal-form">
                <form id="afegirusuariform" data-id="" novalidate>
                    <div class="input_container row nolinia">
                        <input type="hidden" class="text" name="id" id="id" value="">
                        <div class="col-3">
                            <label for="nom">Nom: <span class="required">*</span></label>
                        </div>
                        <div class="field_container">
                            <input type="text" class="text required" name="nom" id="nom" value="" required>
                        </div>
                    </div>
                    <div class="input_container row nolinia">
                        <div class="col-3">
                            <label for="cognoms">Cognoms: <span class="required">*</span></label>
                        </div>
                        <div class="field_container">
                            <input type="text" class="text required" name="cognoms" id="cognoms" value="" required>
                        </div>
                    </div>
                    <div class="input_container row nolinia">
                        <div class="col-3">
                            <label for="dni">DNI: <span class="required">*</span></label>
                        </div>
                        <div class="field_container">
                            <input type="text" class="text required" name="dni" id="dni" value="" required>
                        </div>
                    </div>
                    <div class="input_container row nolinia">
                        <div class="col-3">
                            <label for="dataini">Entrada: </label>
                        </div>
                        <div class="field_container">
                            <input type="text" class="text" name="dataini" id="dataini" value="">
                        </div>
                    </div>
                    <div class="input_container row nolinia">
                        <div class="col-3">
                            <label for="datafi">Sortida: </label>
                        </div>
                        <div class="field_container">
                            <input type="text" class="text" name="datafi" id="datafi" value="">
                        </div>
                    </div>
                    <div class="input_container row nolinia">
                        <div class="col-3">
                            <label for="idsensorh2o">Id sensor H2O: </label>
                        </div>
                        <div class="field_container">
                            <select name="idsensorh2o" id="idsensorh2o">
                            </select>
                        </div>
                    </div>
                    <div class="input_container row nolinia">
                        <div class="col-3">
                            <label for="h2o">Consum H2O: </label>
                        </div>
                        <div class="field_container">
                            <input type="text" class="text nomodif" name="h2o" id="h2o" value="" disabled>
                        </div>
                    </div>
                    <div class="input_container row nolinia">
                        <div class="col-3">
                            <label for="idsensorelec">Id sensor Elec: </label>
                        </div>
                        <div class="field_container">
                            <select name="idsensorelec" id="idsensorelec">
                                <option value="0">-</option>
                            </select>
                        </div>
                    </div>
                    <div class="input_container row nolinia">
                        <div class="col-3">
                            <label for="elec">Consum Elèctric: </label>
                        </div>
                        <div class="field_container">
                            <input type="text" class="text nomodif" name="elec" id="elec" value="" disabled>
                        </div>
                    </div>
                </form>
                <br />
                <button id="afegirusuariguardar">Guardar</button>
                <button id="afegirusuaricancelar">Cancel·lar</button>
            </div>
        </div>
    </div>
    
</body>
<script type="text/javascript" src="js/moment-with-locales.min.js"></script>
<script type="text/javascript" src="js/jquery.js"></script>
<script type="text/javascript" src="js/jquery.knob.min.js"></script>
<script type="text/javascript" src="js/datatables.min.js"></script>
<script type="text/javascript" src="xxxjs/buttons.html5.min.js"></script>
<script type="text/javascript" src="xjs/chart.min.js"></script>
<script type="text/javascript" src="js/Chart.bundle.min.js"></script>
<script type="text/javascript" src="js/wausuaris.js"></script>
<script type="text/javascript" src="js/modal.js"></script>
<script type="text/javascript" src="js/jquery.validate.min.js"></script>
<script type="text/javascript" src="js/jquery.daterangepicker.min.js"></script>
<script type="text/javascript">

</script>
</html>
