<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="css/reset.css">
    <link rel="stylesheet" href="css/datatables.min.css">
    <link rel="stylesheet" href="css/simple-grid.css">
    <link rel="stylesheet" href="css/estils.css">
    <link rel="stylesheet" href="css/navbarmenu.css">
    <title>Pilones</title>
</head>
<body>
    <header>
        <div class="elmenu">
            <a href="/" class="linkmenu">
                <div class="dinsmenu descripcio">home</div>
                <div class="dinsmenu imatge"><img src="images/home-gris.svg" /></div>
            </a>
        </div>
        <div class="elmenu">
            <a href="" class="linkmenu">
                <div class="dinsmenu descripcio">usuaris</div>
                <div class="dinsmenu imatge"><img src="images/avatar-gris.svg" /></div>
            </a>
        </div>
        <div class="elmenu">
            <a href="" class="linkmenu">
                <div class="dinsmenu descripcio">h2o</div>
                <div class="dinsmenu imatge"><img src="images/tap-gris.svg" /></div>
            </a>
        </div>
        <div class="elmenu">
            <a href="" class="linkmenu">
                <div class="dinsmenu descripcio">elec</div>
                <div class="dinsmenu imatge"><img src="images/light-bulb-gris.svg" /></div>
            </a>
        </div>
        <div class="elmenu">
            <a href="" class="linkmenu">
                <div class="dinsmenu descripcio">gràfs</div>
                <div class="dinsmenu imatge"><img src="images/chart-gris.svg" /></div>
            </a>
        </div>
        <div class="elmenu">
            <a href="" class="linkmenu">
                <div class="dinsmenu descripcio">fact</div>
                <div class="dinsmenu imatge"><img src="images/euro-gris.svg" /></div>
            </a>
        </div>
        <div class="elmenu">
            <a href="" class="linkmenu">
                <div class="dinsmenu descripcio">logout</div>
                <div class="dinsmenu imatge"><img src="images/power-button-sign-gris.svg" /></div>
            </a>
        </div>
    </header>
    <div class="container">
        <div id="divtaula" class="row">
            <div class="col-12">
                <div class="titolknob">Últims moviments</div>
                <div id="lataula" class="taules">
                    <table class="datatable" id="taula">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Data/hora</th>
                                <th>Valor</th>
                                <th># sensor</th>
                                <th>Missatge</th>
                                <th>Tipus</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</body>
<script type="text/javascript" src="js/jquery.js"></script>
<script type="text/javascript" src="js/jquery.knob.min.js"></script>
<script type="text/javascript" src="js/datatables.min.js"></script>
<script type="text/javascript" src="xjs/chart.min.js"></script>
<script type="text/javascript" src="js/Chart.bundle.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        alert();
    });
</script>
</html>
